Update programs.clj
mtgred/netrunner pull request #6941
Opened 2023-05-22 10:22 UTC by Tamijo-Netrunner

Odore's first ability `2c: Break all subs` can be used while 3 Virtuals are installed. (Relevant interactions exist where a player wants to do this over the `0c: Break a sub` ability.)

2023-05-22 13:15 UTC, NoahTheDuke requested changes
Gotta update the tests to account for this. And i think it was written this way to make auto pumping and breaking work. Might need to disable that if you can't get it to work together.

2023-07-08 03:28 UTC, NBKelly commented
Closes #6940

2023-09-21 15:58 UTC, NoahTheDuke commented
hey @Tamijo-Netrunner, wanna take another swing at this?

2023-11-15 15:19 UTC, NoahTheDuke commented
Okay, turns out it's slightly trickier than it seems. I'm working on a version of this that should fix the additional issues it raised. Thanks for the initial work!

2023-11-15 15:19 UTC, closed without merging